export const productsSeedData = [
    {
        name: 'Flea And Tick Collar',
        description: 'Best shampoo for your puppies and young adults. Helps in treating skin infections and maintaining a healthy coat.',
        images: ["https://res.cloudinary.com/dfrwmkb42/image/upload/v1721889171/nouva-vet/products/Flea%20And%20Tick%20Collar-1721889170448.webp"],
        category: ['dogs'],
        brand: 'Arichem',
        quantity: '',
        price: 1800,
        discountRate: 0,
        stock: 100,
        featured: true,
        slug: 'flea-and-tick-collar',
    },
    {
        name: 'Vetzyme B plus E',
        description: 'Vettzyme B plus E lorem ipsum dolor sit amet. Lorem ipsum solor sit amet',
        images: ["https://res.cloudinary.com/dfrwmkb42/image/upload/v1721889197/nouva-vet/products/Vetzyme%20B%20plus%20E-1721889196976.webp"],
        category: ['medicine'],
        brand: 'Arichem',
        quantity: '100 tablets',
        price: 1800,
        discountRate: 0,
        stock: 100,
        featured: true,
        slug: 'vetzyme-b-plus-e',
    },
]
const seed2 = [
    {
        name: 'Bravo Dog Adult chicken flavour',
        description: 'Bravo Dog Adult chicken flavour. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet',
        images: ["https://res.cloudinary.com/dfrwmkb42/image/upload/v1721889824/nouva-vet/products/Bravo%20Dog%20Adult%20chicken%20flavour-1721889822217.webp"],
        category: ['dogs', 'food'],
        brand: 'Isinya Feeds',
        quantity: '15 kg',
        price: 4300,
        discountRate: 0,
        stock: 100,
        featured: true,
        slug: 'bravo-dog-adult-chicken-flavour',
        rating: 4.5,
        numReviews: 10
    },
    {
        name: 'DuduKrin Medicated Dog Shampoo',
        description: 'Best shampoo for your puppies and young adults. Helps in treating skin infections and maintaining a healthy coat.',
        images: ["https://res.cloudinary.com/dfrwmkb42/image/upload/v1721889328/nouva-vet/products/DuduKrin%20Medicated%20Dog%20Shampoo-1721889327145.webp"],
        category: ['dogs'],
        brand: 'Arichem',
        quantity: '500 ml',
        price: 1000,
        discountRate: 10,
        stock: 100,
        featured: true,
        slug: 'dudukrin-medicated-dog-shampoo',
        rating: 4.5,
        numReviews: 10
    },
    {
        name: 'DuduKrin Medicated Dog Shampoo',
        description: 'Best shampoo for your puppies and young adults. Helps in treating skin infections and maintaining a healthy coat.',
        images: ['https://example.com/dudukrin1.jpg', 'https://example.com/dudukrin2.jpg'],
        category: ['dogs'],
        brand: 'Arichem',
        quantity: '250 ml',
        price: 650,
        discountRate: 0,
        stock: 100,
        featured: true,
        slug: 'dudukrin-medicated-dog-shampoo',
        rating: 4.5,
        numReviews: 10
    },
    {
        name: 'DuduKrin Medicated Dog Shampoo',
        description: 'Best shampoo for your puppies and young adults. Helps in treating skin infections and maintaining a healthy coat.',
        images: ['https://example.com/dudukrin1.jpg', 'https://example.com/dudukrin2.jpg'],
        category: ['dogs'],
        brand: 'Arichem',
        quantity: '1 litre',
        price: 1750,
        discountRate: 0,
        stock: 100,
        featured: false,
        slug: 'dudukrin-medicated-dog-shampoo',
        rating: 4.5,
        numReviews: 10
    },
    {
        name: 'Paw-Paw fish Flavour Adult Cat Food',
        description: 'Paw-Paw fish Flavour Adult Cat Food.Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet',
        images: ["https://res.cloudinary.com/dfrwmkb42/image/upload/v1721889457/nouva-vet/products/Paw-Paw%20fish%20Flavour%20Adult%20Cat%20Food-1721889455329.webp"],
        category: ['cats', 'food'],
        brand: 'Isinya Feeds',
        quantity: '1.5 kg',
        price: 1500,
        discountRate: 0,
        stock: 100,
        featured: true,
        slug: 'Paw-Paw-fish-Flavour-Adult-Cat-Food',
        rating: 4.5,
        numReviews: 10
    },
    {
        name: 'Bravo Active',
        description: 'Bravo Active. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet',
        images: ["https://res.cloudinary.com/dfrwmkb42/image/upload/v1721889762/nouva-vet/products/Bravo%20Active-1721889760395.webp"],
        category: ['dogs', 'food'],
        brand: 'Isinya Feeds',
        quantity: '15 kg',
        price: 4500,
        discountRate: 0,
        stock: 100,
        featured: true,
        slug: 'bravo-active',
        rating: 4.5,
        numReviews: 10
    },
    {
        name: 'Dr Yorkie Dog Shampoo',
        description: 'Dr Yorkie Dog Shampoo. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet',
        images: ['https://example.com/aquarium-kit1.jpg'],
        category: ['dogs'],
        brand: 'AquaWorld',
        quantity: '500 ml',
        dimensions: '',
        price: 500,
        discountRate: 0,
        stock: 20,
        featured: false,
        slug: 'dr-yorkie-dog-shampoo',
        rating: 4.4,
        numReviews: 30
    },

    {
        name: 'Catnip Mouse Toy',
        description: 'Interactive toy for cats. Filled with organic catnip to keep your feline friend entertained for hours.',
        images: ['https://example.com/catnip-mouse1.jpg'],
        category: ['cats'],
        brand: 'PetPlay',
        quantity: '1 piece',
        dimensions: '10cm x 5cm',
        price: 5.99,
        discountRate: 0.1,
        stock: 200,
        featured: false,
        slug: 'catnip-mouse-toy',
        rating: 4.2,
        numReviews: 50
    },
    {
        name: 'Premium Dog Food',
        description: 'High-quality, grain-free dog food suitable for all life stages.',
        images: ['https://example.com/premium-dog-food1.jpg', 'https://example.com/premium-dog-food2.jpg'],
        category: ['dogs'],
        brand: 'NutriCanine',
        quantity: '15 kg',
        price: 54.99,
        discountRate: 0.1,
        stock: 50,
        featured: false,
        slug: 'premium-dog-food',
        rating: 4.8,
        numReviews: 120
    },
    {
        name: 'Cat Tree Condo',
        description: 'Multi-level cat tree with scratching posts, perches, and hideaway spots.',
        images: ['https://example.com/cat-tree1.jpg', 'https://example.com/cat-tree2.jpg'],
        category: ['cats'],
        brand: 'FelineFun',
        quantity: '1 unit',
        dimensions: '60cm x 60cm x 170cm',
        price: 89.99,
        discountRate: 0.15,
        stock: 30,
        featured: true,
        slug: 'cat-tree-condo',
        rating: 4.6,
        numReviews: 85
    },
    {
        name: 'Aquarium Starter Kit',
        description: 'Complete 20-gallon aquarium set with filter, lighting, and decor.',
        images: ['https://example.com/aquarium-kit1.jpg'],
        category: ['fish'],
        brand: 'AquaWorld',
        quantity: '1 set',
        dimensions: '60cm x 30cm x 40cm',
        price: 129.99,
        discountRate: 0,
        stock: 20,
        featured: false,
        slug: 'aquarium-starter-kit',
        rating: 4.4,
        numReviews: 30
    },
    {
        name: 'Bird Cage Playgym',
        description: 'Colorful and interactive playgym for parakeets, cockatiels, and other small birds.',
        images: ['https://example.com/bird-playgym1.jpg', 'https://example.com/bird-playgym2.jpg'],
        category: ['birds'],
        brand: 'ChirpyToys',
        quantity: '1 unit',
        dimensions: '40cm x 30cm x 45cm',
        price: 34.99,
        discountRate: 0.05,
        stock: 40,
        featured: false,
        slug: 'bird-cage-playgym',
        rating: 4.7,
        numReviews: 22
    },
    {
        name: 'Small Animal Exercise Ball',
        description: 'Safe and fun exercise ball for hamsters, gerbils, and other small pets.',
        images: ['https://example.com/exercise-ball.jpg'],
        category: ['small_pets'],
        brand: 'TinyTracks',
        quantity: '1 piece',
        dimensions: '15cm diameter',
        price: 9.99,
        discountRate: 0,
        stock: 100,
        featured: false,
        slug: 'small-animal-exercise-ball',
        rating: 4.5,
        numReviews: 60
    },
    {
        name: 'Reptile Terrarium',
        description: 'Glass terrarium ideal for snakes, lizards, or amphibians with front opening doors.',
        images: ['https://example.com/reptile-terrarium1.jpg', 'https://example.com/reptile-terrarium2.jpg'],
        category: ['reptiles'],
        brand: 'HerpHabitat',
        quantity: '1 unit',
        dimensions: '60cm x 45cm x 45cm',
        price: 79.99,
        discountRate: 0.1,
        stock: 15,
        featured: true,
        slug: 'reptile-terrarium',
        rating: 4.9,
        numReviews: 28
    },
    {
        name: 'Automatic Pet Feeder',
        description: 'Programmable feeder for cats and dogs with portion control and scheduling.',
        images: ['https://example.com/pet-feeder.jpg'],
        category: ['dogs', 'cats'],
        brand: 'SmartFeeder',
        quantity: '1 unit',
        price: 69.99,
        discountRate: 0.2,
        stock: 35,
        featured: true,
        slug: 'automatic-pet-feeder',
        rating: 4.3,
        numReviews: 95
    },
    {
        name: 'Dog Training Clicker',
        description: 'Simple yet effective tool for positive reinforcement training.',
        images: ['https://example.com/dog-clicker.jpg'],
        category: ['dogs'],
        brand: 'TrainRight',
        quantity: '2 pack',
        price: 500,
        discountRate: 0,
        stock: 200,
        featured: true,
        slug: 'dog-training-clicker',
        rating: 4.6,
        numReviews: 150
    },
    {
        name: 'Cat Litter Box Enclosure',
        description: 'Stylish wooden cabinet that discreetly houses your cat\'s litter box.',
        images: ['https://example.com/litter-enclosure1.jpg', 'https://example.com/litter-enclosure2.jpg'],
        category: ['cats'],
        brand: 'ModernPet',
        quantity: '1 unit',
        dimensions: '75cm x 50cm x 65cm',
        price: 129.99,
        discountRate: 0.1,
        stock: 25,
        featured: false,
        slug: 'cat-litter-box-enclosure',
        rating: 4.4,
        numReviews: 55
    },
    {
        name: 'Live Aquarium Plants Bundle',
        description: 'Assortment of live aquatic plants to create a natural underwater landscape.',
        images: ['https://example.com/aquarium-plants.jpg'],
        category: ['fish'],
        brand: 'GreenAqua',
        quantity: '10 plants',
        price: 24.99,
        discountRate: 0,
        stock: 30,
        featured: false,
        slug: 'live-aquarium-plants-bundle',
        rating: 4.2,
        numReviews: 18
    },
    {
        name: 'Parrot Foraging Toys',
        description: 'Set of challenging toys to keep your parrot mentally stimulated.',
        images: ['https://example.com/parrot-toys1.jpg', 'https://example.com/parrot-toys2.jpg'],
        category: ['birds'],
        brand: 'BeakBusy',
        quantity: '5 pieces',
        price: 39.99,
        discountRate: 0.15,
        stock: 40,
        featured: true,
        slug: 'parrot-foraging-toys',
        rating: 4.7,
        numReviews: 33
    },
    {
        name: 'Guinea Pig Fleece Hideaway',
        description: 'Cozy fleece hideout for guinea pigs, also suitable for other small animals.',
        images: ['https://example.com/guinea-hideaway.jpg'],
        category: ['small_pets'],
        brand: 'CozyCreatures',
        quantity: '1 piece',
        dimensions: '30cm x 20cm x 15cm',
        price: 14.99,
        discountRate: 0,
        stock: 60,
        featured: false,
        slug: 'guinea-pig-fleece-hideaway',
        rating: 4.8,
        numReviews: 42
    },
    {
        name: 'UVB Lamp for Reptiles',
        description: 'Full spectrum UV lamp crucial for the health of many reptile species.',
        images: ['https://example.com/uvb-lamp.jpg'],
        category: ['reptiles'],
        brand: 'ReptileRays',
        quantity: '1 unit',
        price: 34.99,
        discountRate: 0.05,
        stock: 50,
        featured: true,
        slug: 'uvb-lamp-for-reptiles',
        rating: 4.9,
        numReviews: 75
    },
    {
        name: 'Elevated Dog Bed',
        description: 'Raised mesh bed keeps your dog cool and comfortable, ideal for indoor and outdoor use.',
        images: ['https://example.com/elevated-dog-bed1.jpg', 'https://example.com/elevated-dog-bed2.jpg'],
        category: ['dogs'],
        brand: 'PawComfort',
        quantity: '1 unit',
        dimensions: '90cm x 60cm x 20cm',
        price: 29.99,
        discountRate: 0.1,
        stock: 75,
        featured: false,
        slug: 'elevated-dog-bed',
        rating: 4.5,
        numReviews: 88
    },
    {
        name: 'Interactive Laser Cat Toy',
        description: 'Automatic rotating laser pointer to keep your cat active and entertained.',
        images: ['https://example.com/laser-cat-toy.jpg'],
        category: ['cats'],
        brand: 'FunFelix',
        quantity: '1 piece',
        price: 19.99,
        discountRate: 0,
        stock: 100,
        featured: true,
        slug: 'interactive-laser-cat-toy',
        rating: 4.3,
        numReviews: 112
    },
    {
        name: 'Aquarium Testing Kit',
        description: 'Complete kit for testing pH, ammonia, nitrite, and nitrate levels in freshwater aquariums.',
        images: ['https://example.com/aquarium-test-kit.jpg'],
        category: ['fish'],
        brand: 'AquaCheck',
        quantity: '100 tests',
        price: 22.99,
        discountRate: 0.05,
        stock: 60,
        featured: false,
        slug: 'aquarium-testing-kit',
        rating: 4.7,
        numReviews: 65
    },
    {
        name: 'Parakeet Swing Set',
        description: 'Variety of swings and perches to add to your bird\'s cage for exercise and entertainment.',
        images: ['https://example.com/parakeet-swings.jpg'],
        category: ['birds'],
        brand: 'FeatheredFun',
        quantity: '5 pieces',
        price: 12.99,
        discountRate: 0,
        stock: 90,
        featured: false,
        slug: 'parakeet-swing-set',
        rating: 4.4,
        numReviews: 29
    },
    {
        name: 'Hamster Silent Exercise Wheel',
        description: 'Quiet, smooth-running wheel for hamsters and other small rodents.',
        images: ['https://example.com/hamster-wheel1.jpg', 'https://example.com/hamster-wheel2.jpg'],
        category: ['small_pets'],
        brand: 'QuietRun',
        quantity: '1 unit',
        dimensions: '15cm diameter',
        price: 16.99,
        discountRate: 0.1,
        stock: 70,
        featured: true,
        slug: 'hamster-silent-exercise-wheel',
        rating: 4.6,
        numReviews: 54
    },
    {
        name: 'Reptile Climbing Branch',
        description: 'Natural wood branch for climbing and basking, suitable for a variety of reptiles.',
        images: ['https://example.com/reptile-branch.jpg'],
        category: ['reptiles'],
        brand: 'NaturalHabitat',
        quantity: '1 piece',
        dimensions: 'Approx. 40cm - 50cm length',
        price: 9.99,
        discountRate: 0,
        stock: 40,
        featured: false,
        slug: 'reptile-climbing-branch',
        rating: 4.5,
        numReviews: 37
    },
    {
        name: 'Dog Grooming Kit',
        description: 'Complete set of grooming tools including brushes, combs, nail clippers, and more.',
        images: ['https://example.com/dog-grooming-kit1.jpg', 'https://example.com/dog-grooming-kit2.jpg'],
        category: ['dogs'],
        brand: 'GroomPro',
        quantity: '10 pieces',
        price: 45.99,
        discountRate: 0.2,
        stock: 55,
        featured: true,
        slug: 'dog-grooming-kit',
        rating: 4.8,
        numReviews: 103
    }
]
